name: Build Check

on: [push]
jobs:
  build_check:
    name: "Build Check"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install deps
      shell: bash
      run: |
        pip3 install build
      
    - name: Build
      shell: bash
      run: |
        python3 -m build
